//THIS DOCUMENT WAS WRITTEN AND MADE BY NOELNIM NAD HAMPU07. IT IS UNDER COPYRIGHT AND YOU ARE NOT ALLOWED TO SHARE, DISTRIBUTE OR USE THIS CODE IN ANYWAY SHAPE OR FORM (C) 2021

document.addEventListener('DOMContentLoaded', () => 
{
    console.log('MILK');
})